#!/bin/sh
db="db.sqlite"
mkb10="1.2.643.5.1.13.13.11.1005_2.27.csv"
mkbo="1.2.643.5.1.13.13.11.1486_2.7.csv"

# Delete current base and create the new one
rm -f $db
cat schema.sql | sqlite3 $db

# Dump data to database from csv files
for table in mkb10 mkbo; do
  file="resources/$(eval echo \$${table})"
  sqlite3 $db -cmd ".mode csv" ".separator ;" ".import --skip 1 $file $table"
done

# Convert empty fields to NULL value
for field in parent_id code date; do
  echo "update mkb10 set $field = NULL where length($field) = 0;" | sqlite3 $db
done
for field in parent_id code; do
  echo "update mkbo set $field = NULL where length($field) = 0;" | sqlite3 $db
done

chmod 666 $db
